version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./backend/psql_data:/var/lib/postgresql/data
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
  frontend:
    image: example-frontend
    build: ./example-frontend/
    ports:
      - 3001:5000
  backend:
    image: example-backend
    build: ./example-backend/
    ports:
      - 3000:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:3001
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
  