version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./backend/psql_data:/var/lib/postgresql/data
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
  frontend:
    image: example-frontend
    build: ./example-frontend/
    ports:
      - :5000
  backend:
    image: example-backend
    build: ./example-backend/
    ports:
      - :8080
    environment:
      - REQUEST_ORIGIN=http://localhost:80
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend